install-source.rst
"su -" will actually put you in the right directory... doing the "cd zammad" will actually trigger an error because /opt/zammad doesn't exist
=> Typo - no need to 'cd zammad'

contributing-install-source.rst
wget is not in the prerequisites, when curl is
=> Use curl instead of wget

admin-console.rst
It seems that the locale in the example needs to be 'de-de', not just 'de'. Also, running without created_by_id/updatead_by_id returns an error.
=> Update Add Translation example

api-intro.rst
This will add a reference to the android API Client.
As discussed on https://community.zammad.org/t/zammad-android-client/2946/3
=> adding android-api-client to docs

console/working-on-tickets.rst
Affected documentation part:
https://docs.zammad.org/en/latest/console/working-on-tickets.html#make-new-states-available-to-ui
We currently hold the following code snipped:
```
attribute = ObjectManager::Attribute.get(
object: 'Ticket',
name: 'state_id',
)
```
The above actually is wrong and suggest to insert the created states ID which is wrong. The snipped needs to be like this:
```
attribute = ObjectManager::Attribute.get(
object: 'Ticket',
name: 'state_name',
)
```
This PR fixes this issue and also fixes a typo / visual thing for the earlier corrected "adding a time picker for pending states".
Martin, could you please check the code snippet-Part? :)
Thank you!
=> Fixing code snipped for making states available to UI

console/working-on-tickets.rst
This commit extends our docs by commands on "How can I restrict my customers to only change specific ticket states?".
This came up on the following community thread:
https://community.zammad.org/t/prevent-the-customer-from-changing-the-status/3164
@Thorsten, can you please take a look? :)
=> enhance console documentation for limiting state changes for customers

appendix-backup-and-restore.rst
This has been discussed in https://community.zammad.org/t/db-backup-password/3256
and will help users that don't want to run Backups as root-user.
@thorsteneckel can you please review this?
=> added further remarks on backing up as non root-user

install-source.rst
We've overseen a ruby version in the docs  just correcting this from 2.4.4 to 2.5.5
=> correct ruby dependency

install-elasticsearch.rst
See issue https://github.com/zammad/zammad/issues/2824
Currently we only support ES up to 7.4.X
=> added warning for ES 7.5 being incompatible

install-source.rst
- Debian/Ubuntu has replaced 'su' implementation with util-linux
(see: "https://sources.debian.org/src/util-linux/2.33.1-0.1/debian/util-linux.NEWS/")
- from then on 'su' should be used with '-' to get a clean environment
=> Fixed user switch to zammad user (behaviour of 'su' changed in Debian)

admin/console/dangerzone-for-experts.rst
Per comments on 641f241 by Marcel Herrguth:
> You merged two code blocks \[in admin/console/dangerzone-for-experts.rst\]
> that were divided for a important reason: The user not to run it
> immediately
>
> (I learned in the community that many people have issues reading and
> that sometimes causes bad things)
This commit uses definition lists to clearly separate the steps of
deleting DB records in the Console guides.
=> Increase visual separation in Danger Zone code samples

admin/console.rst, admin/console/hidden-settings.rst, admin/console/other-usefull-commands.rst, admin/console/working-on-ticket-articles.rst, admin/console/working-on-tickets.rst, admin/console/working-on-users.rst, admin/console/zammad-settings.rst
This pull requests comes in two flavors:
* It fixes the wording from "our Community" to "the Community". This is our preferred way to reference the Zammad community forum. This is a small wording thingie.
* It introduces console commands on how to change note articles to a communication article in order to be considered by our SLA calculation. It also features a warning of what will change so the scope hopefully is clear.
@Ryan - can you please have a look when you find some spare time?
I tried to adjust to your styling and hope it's fitting. Wording might be off though. :>
=> Add ticket article commands for console (SLA communication)

api/intro.rst, install/docker-compose.rst, install/source.rst, install/update.rst, prerequisites/software.rst
This pull request mainly concentrates on adjusting requirenments.
This also includes a make over of how we communicate supported and/or required versions for ruby and elasticsearch. This has the benefit that some warning colors can disappear from the docs.
Beside of that I fiddled around with wording. :>
**Important:** We can't merge this before releasing 3.4 (or 1-2 hours before), as it might confuse users installing 3.3 at this moment.
=> Adjust documentation for upcoming 3.4 release

prerequisites/software.rst
Upon update of our on-premise Zammad 3.3 to 3.4 today, we also updated Elasticsearch from 7.5 to 7.7.1 on Debian 9 and it works perfectly with Zammad 3.4+.
=> Updated supported ES version for Zammad 3.4+

appendix/configure-env-vars.rst, prerequisites/hardware.rst
-- low priority as of now --
This PR adds a quite useful environment variable to allow adminsitrators to have more than one session worker doing stuff.
Session workers are dedicated workers for all regards of active user sessions. 
This approach does provide more steam for other scheduler based jobs and potentially doesn't block them.
I also was so keen and added remarks for options that might help on performance tuning and also linked the environment page on hardware information page.
Right now a own tuning page is not yet good enough, because such a comprehensive writeup of  such tips -currently- is out of my time scope.
I'd like to stay this way until we have the ressources. I just don't want to make people believe there are tons of magical tipps when they'll only find like 2 …
=> Extending environment variable documentation

install/centos.rst
The 'Only worker process' block was missing the start parameter.
=> fix session missing the 'start' parameter

appendix/configure-env-vars.rst, prerequisites/hardware.rst
Setting WEB_CONCURRENCY and ZAMMAD_SESSION_JOBS_CONCURRENT is not an option if hardware is not upgradable. It's always a option.
Enhanced link to certain settings via #performance-tuning anker.
=> Improved Performance Tuning.

api/tags.rst
With Zammad 3.5 API endpoints for tags change.
This pull requests updates the documentation to provide this change.
While I was at it, I also reduced text and lines (more compressed now) which is the look and feel I currently think of for the API docsoverall. The examples and code have been validated and corrected where needed.
=> Adjust API endpoint documentation for Zammad 3.5

admin/console/other-usefull-commands.rst
Found here: https://community.zammad.org/t/cant-create-tickets-per-mail-database-error/1077/2 and sorely missed in the documentation :)
=> other-usefull-commands.rst: added Channel::EmailParser.process_unprocessable_mails

api/intro.rst
* Transforms the Markdown syntax into rst syntax.
* Gives the link a proper name for better accessibility.
* Automated tools (like screen readers) may list all links on a page and a link with the name "here" doesn't tell you what to expect.
=> Intro: Correct HTTP Basic Auth link

contributing/ci.rst
Section with required steps to run the new RSpec tests locally has been added. In the absence of a good developer manual, perhaps this should hopefully ease the pain for new contributors, considering new test cases are required for any changes. While it is possible to gather this information from the other maintainers, sometimes it's nice to find everything in one place.
(Based on the `master` branch, as previous [PR#162](https://github.com/zammad/zammad-documentation/pull/162) was erroneously based on `develop`.)
Reference: [zammad/zammad#3425 (comment)](https://github.com/zammad/zammad/pull/3425#issuecomment-785184981)
=> Added section for running RSpec tests locally.

prerequisites/software.rst
This pull request raises minimum database server versions to reflect current compatibilities.
MySQL: 5.6 → 5.7
MariaDB: 10.0 → 10.3
---
This reflects test environments and ensures e.g. big indexes working as intended.
@thorsteneckel Can you please have a look if that's okay from your end as well?
Thanks!
=> Raise minimum required database server versions

install/source.rst
This might be a temporary solution as found on https://github.com/rvm/rvm/issues/5096 
RVM documentation currently is outdated and provides a solution that no longer works.
=> Maintenance: Update keyserver to use for RVM

install/source.rst, install/source/include-get-the-source.rst, prerequisites/software.rst
This pull request improves the unpack commands for github based tars (they contain a folder we don't want). This reduces load on administrators.
Additionally this PR enhances input on what MySQL servers need to provide to help users choosing that (not favored) way.
=> Enhance untar command for easier usage and enhance mysql information

install/elasticsearch/indexed-attributes.rst
This commit fixes wording for the `done` attribute which initially was incorrect. This might help admins, especially in reporting situations, to understand the scope of this attribute.
=> Maintenance: Fix wording for done-attribute (CTI-Log)

admin/console/working-on-tickets.rst
This removes obsolete pending till commands, adds a hint for Core Workflows doing the job (and allowing it via UI) and provide a console snippet just in case it's needed.
=> Fixes #201 - Remove obsolete pending till; Add Core Workflows hints

install/elasticsearch.rst, install/package.rst
This pull request adds debian 11 support and also switches to "signed-by" logics for apt like installations. 
This is due Debian 11 and Ubuntu 22 soft-deprecating `apt-key` (which throws warnings). We don't want warnings.
=> Closes #209 - Debian 11 support

appendix/configure-env-vars.rst
Added a hint on how to get the current value of an option via "zammad config:get".
=> Added a "config:get"-hint

install/includes/nodejs/centos.rst, install/includes/nodejs/debian.rst, install/includes/nodejs/suse.rst, install/includes/nodejs/ubuntu.rst, install/package.rst, prerequisites/software.rst
- Installation instructions changed to use LTS versions of Node.js rather than the most recent.
- Removed Node.js installation instructions for package installations as Node.js gets bundled by packager.io.
=> Update for Node.js 16 dependency of Zammad 5.2.

migration/index.rst
This has been raised quite often lately, time to note it right away.
=> Explicitely add "all or nothing" to migration limitations

prerequisites/software.rst
This adds a clear warning that Ubuntu 22 is not yet supported due to its dependencies that Zammad currently does not fulfill.
JFI: Can safely be merged into the destination branch configured if everything is good to go. ✌️
=> Maintenance: Add strict warning that Ubuntu 22 is not yet supported

appendix/backup-and-restore/clear-the-cache.include.rst, install/update.rst, migration/includes/commands-after-migration.include.rst
This will avoid deprecation warnings in the logs and avoid problems with Zammad 6.
=> Update deprecated 'Cache.clear' calls to 'Rails.cache.clear'.

appendix/configure-env-vars.rst
This new note hopefully helps administrators to understand the user / superuser context and act accordingly.
I also moved the database connection remark for the tuning section up to the start of the section as some administrators don't scroll down far enough to be warned.
=> Add privilege hint for APP_RESTART_CMD

appendix/migrate-to-postgresql.rst
Improved the current migration documentation with the fix for the JSON values handling (zammad/zammad/issues/4431).
There is now a rake task (when the related issue is merged) to generate the "pgloader-command" file which needs to be used so that the JSON values are migrated correctly.
=> Improved mysql/mariadb to postgresql migration for JSON values (zammad/zammad/issues/4431).

getting-started/configure-webserver.rst
It is bad practice to have config files directly in sites-enabled for any webserver using that directory. There should only be symbolic links there.
I changed the mentions in the docs to the sites-available directory.
=> Correct paths from sites-enabled to sites-available

install/source/include-get-the-source.rst
`zammad-latest.*` on FTP will be updated by CI whenever a commit is applied to `stable`. Let's update the docs for this as well.
=> Maintenance: Change to the FTP download URL now that we have continuous delivery for source archives

prerequisites/software.rst
There will also be announcements on other channels, but the documentation should also give a hint about it.
This can be merged after review, don't need to wait for Zammad 5.4.
Not sure if we can/need to make this more prominent on the software requirements page somehow.
=> Include a hint that Redis will be a regulard dependency from Zammad 6.0 onwards.

appendix/privacy.rst
Related proposal MR for https://github.com/zammad/zammad/issues/4437 fix
=> DRAFT v5.4: Fixes #4437 - DataPrivacy tasks never are cleaned up.

api/organization.rst, appendix/configure-env-vars.rst
The route to delete an organization is ``/api/v1/organizations/{id}`` instead of ``/api/v1/organization/{id}``
=> Fixes invalid endpoint documentation

.github/workflows/docs.yml, .github/workflows/test.yml, .rstcheck.cfg
Job example (from the fork): [main](https://github.com/dvuckovic/zammad-documentation/actions/runs/5666763737)
=> Maintenance: Add CI pipeline based on Github workflows.

api/ticket/articles.rst
Adjusted some examples with the new attribute.
=> Fixes #1103 - 'time_unit' attribute is not propagated over ticket articles API

migration/otrs.rst
Znunys addon service currently throws 404 errors for all addons the OTRS migration requires.
For this reason I replaced these with our own hosted source for our users to use.
This change should also receive a backport to `main` to solve the current `404` situation.
=> Maintenance: Replace Znuny hosted addons with our own hosting source

appendix/configure-env-vars.rst, install/docker-compose/environment.rst
Change docker compose env variables into a table format for easy readability.
Attaching a screenshot for visual reference
=> Change docker compose env variables to table format

install/includes/firewall-and-selinux.rst, install/includes/postgres-dependencies.rst, install/includes/postgres-installation.rst, install/package.rst, prerequisites/software.rst
- Change to Node 18.
- Drop Debian 10, Ubuntu 18, CentOS7, and SLES 12 which are unsupported after deprecation with Zammad 6.1.
=> Switch to Node 18 requirement and drop unsupported linux distributions.

install/source.rst
This is related to https://github.com/zammad/zammad/pull/4883
The postgresql connection adapter does not support a `timeout` option.
=> Remove timeout option from db connection configuration 

install/source.rst
The Zammad `Gemfile` and `Gemfile.lock` don't reference any sqlite-related gems anymore, those packages are probably not needed anymore.
=> Remove sqlite3-related packages from recommended packages

install/docker-compose.rst
Follow-up for https://github.com/zammad/zammad-docker-compose/issues/382. The manual docker compose download instructions were wrong, as they didn't cover all required files. I now suggest a simpler method that will get all files and also preserve file permissions.
=> Improve docker compose manual download instructions.

install/elasticsearch.rst
- By default Elasticsearch 8 will use an http**s** connection
- Add commands to define Elasticsearch user / password
=> Elasticsearch 8 - Add a note for default configuration

api/user-access-token.rst
I tried to get a token with basic auth, but failed with the given example. The response said, I need to provide "name". Also, after I got the correct json, the response I got was "token", not "name".
=> Fix token creation documentaion

admin/console/other-useful-commands.rst
Rather than removing the command example completely at this point, a friendly warning is put on top with a link to the relevant section in the admin docs.
This should be communicated to the team, and after collecting their feedback possibly dropped later. Note that there are other similar commands like this which are obsolete with Zammad 6.3.
=> Fixes #445 - Add link to translation chapter as an alternative to the Rails command.

appendix/reporting-tools-thirdparty/grafana.rst
The `worldmap-panel` plugin in Grafana has a builtin panel `geomap` which replaces the plugin.
The Dashboards have been updated to reflect the obsolation, thus the documentation should as well. :-)
As this is already live on grafana.com and our Grafana-Repo, this is save to be put into stable as well.
=> Maintenance: Drop obsolete worldmap-panel plugin requirement

api/group.rst
The given and requested "email_address_id" should be the same as in the response.
Makes no sense to return another "email_address_id" than requested.
=> email_address_id 3

admin/console.rst, install/elasticsearch.rst
Reverts zammad/zammad-documentation#694
=> Revert "Fixes #691 - Added command for adding specific ES index"
