zammad/zammad-documentation

- install-source.rst
Reverts zammad/zammad-documentation#7
> Revert "Update install-source.rst"

- migration-otrs.rst
Add missing otrs plugin dependency.
For a rails novice it might be good to know, how to actually start the shell.
> Add some more information for OTRS migration

- general-glossary.rst
changed from case to ticket during the last months
> fixed term

- admin-webfrontend-security-thirdparty.rst
Added text with the correct URI because the image shows incorrect settings.
> Update google OAUTH configuration

- prerequisites-software.rst
> fixed Ruby version, follow Zammad v.2.3.0

- admin-console.rst
> set password for user in console

- api-ticket-article.rst
fix a mistake on documentation, should be in JSON format and not ruby hash
> should not be in ruby hash

- install-docker-compose.rst
Fixed spelling mistake line 14
> Fixed spelling mistake line 14

- install-source.rst
With these changes I was able to install zammad on ubuntu1804
> Ubuntu1804

- install-docker-compose.rst
it helps me to solve https://github.com/zammad/zammad-docker-compose/issues/80
> Added Port compatibility paragraph

- appendix-repo-file.rst
- install-elasticsearch.rst
- install-source.rst
- install-ubuntu.rst
@monotek is this update for 18.04 OK?
If so, please ping back to me. 
Thanks
> Added Ubuntu 18.04 and Reset instructions

- install-univention.rst
I improved the Univention specific wording and also tried to make the text reading more fluently.
> Improved wording regarding Univention products

- api-tags.rst
Fix documentation on API of Tags
> Minor change on URL of DELETE and RENAME

- admin-console.rst
- install-univention.rst
- univention/issues-you-might-encounter.rst
- univention/running-console-commands-on-univention.rst
This will introduce subpages with info on how to use the console within UCS and move possible issues to a subpage as well.
This will provide overview, as otherwise the page will keep growing.
> Further information section

- install-univention.rst
- univention/app-settings.rst
This documentary will explain how the app-settings work (and why they might not ;) )
> Introducing App-Settings to Univention-App

- console/other-usefull-commands.rst
This commit will help to translate attributes whenever needed.
> adding hints for attribtue translation

- console/working-on-tickets.rst
Enhanced ` Add a date and time picker (pending till) for pending states`.
> Add a date and time picker (pending till) for pending states

- appendix-backup-and-restore.rst
This commit cleans up the documentation and changes my dirty palceholder to something better.
> remove placeholder text

- admin-console.rst
- install-univention.rst
- univention/app-settings.rst
- univention/issues-you-might-encounter.rst
- univention/running-console-commands-on-univention.rst
This pull request holds:
* cleanup of the structure (moved parts to own subpages)
* addition to possible issues you might encounter
* Introduction to App-Settings that will be available from 3.1.0-7 within Univention universe
> Enhancing / Updating Univention Zammad-App documentationary

- admin-console.rst
- appendix-privacy.rst
- console/dangerzone-for-experts.rst
- console/working-on-chat.rst
This extends our privacy information by local storage information. This might help administrators to overview the data retention times.
@thorsteneckel
Can you please take a look and especially check that I got the timings right?
If not, I'll gladly correct them. Also, if you think I missed something out, please let me know!
> extend privacy remarks

- install-debian.rst
I'm not an expert, I haven't performed the install yet, I might be missing some instructions.
> update for Debian 10

- install-elasticsearch.rst
Reverts zammad/zammad-documentation#114
https://github.com/zammad/zammad/issues/2824 is resolved
> Revert "added warning for ES 7.5 being incompatible"

- install-source.rst
see Zammad Issue #2489 (https://github.com/zammad/zammad/issues/2489)
> added missing dependency for Ubuntu 18.04

- console/working-on-tickets.rst
> fix typo from new to edit

- admin/console/working-on-tickets.rst
`articles_ids` seems to be the wrong method, instead it's `article_ids`
> Little typo

- install/kubernetes.rst
From https://zammad.github.io to https://zammad.github.io/zammad-helm
> Fix zammad-helm repo URL

- install/elasticsearch.rst
- prerequisites/software.rst
This pull request updates Elasticsearch requirements and options users with Zammad 4.0+ can choose of.
It also removes no longer required information.
> Update Elasticsearch Dependencies, possible packages and Zammad requirements

- install/source/include-get-the-source.rst
As noted in https://github.com/zammad/zammad/issues/3477#issuecomment-822550901 using the FTP file contains the inital release. 
Also i changed the Here Link
Update of #175
> Changed default file source

- install/docker-compose/environment.rst
> Updating variables documentation

- install/source/include-environment.rst
- install/source/include-rvm-install-ruby.rst
- prerequisites/software.rst
To be merged when 2.6.8 is merged into `stable` for 4.1.1 rolling updates
> Update ruby version to 2.6.8

- appendix/single-sign-on.rst
This PR improves the secret generation on windows side to no longer use passwords on command line, but instead prompt for it. 
It also fixes smaller typos / issues and provides a new FAQ part to help further on troubleshooting.
> Maintenance: Fix command errors, add FAQ & improve commands

- install/source.rst
- install/source/include-chmod-database-yml.rst
- install/update.rst
As per issue https://github.com/zammad/zammad/issues/3828
> Maintenance: Add chmod command for database.yml on source code installation and update

- api/ticket.rst
- api/ticket/links.rst
Hi everyone,
I decided to create another page for linking tickets as I was writing an integration to move from a custom ticket-system to Zammad, therefore I needed to adapt the linking of the tickets as well. After some research in the community forums like https://community.zammad.org/t/link-tickets-as-child-via-api-call/244 or https://community.zammad.org/t/linking-tickets-via-api/3839 which does not contain any answer, I have decided to go further in order to solve my problem. Maybe this documentation will help some people in similar situations.
I'm open for any feedback. 
Just another thing beforehand: At the GET part I have posted a full response (which is quite big). I was struggling if a shortened version would be better. In my opinion the more information the better to work with. …
> Add documentation for linking tickets

- admin/console/working-on-users.rst
Added "Remove password for user"-section to the console documentation on how to modify the User-object.
> New section on how to remove a user password via console

- appendix/troubleshooting.rst
- appendix/troubleshooting/index.rst
- index.rst
After having trouble with missing data from the Web-UI and realizing this seems to be a common occurence I was asked to create an addition for the documentation.
I'm hoping this could be extended in the future to add more common issues and their fixes as well as frequently asked questions to reduce opened GitHub issues without creating the same forum threads again and again.
First time using Sphinx / ReStructuredText so I hope I didn't do any major mistakes 😄
Original Issue: https://github.com/zammad/zammad/issues/3662
> created troubleshooting/faq section and added paragraph about elasticsearch issues

- install/source.rst
- install/update.rst
This PR adds the required locale and translation sync in order for Zammad to update it's translations in source code installations.
> Fixes #230 - Source code installation do not reflect all required steps

- install/docker-compose/environment.rst
These changes have been introduced with Zammad 5.1 and seem to have slipped. :)
> Maintenance: Extend and update docker-compose environment list

- appendix/configure-env-vars.rst
- install/includes/manage-services.rst
- install/source.rst
- install/update.rst
- prerequisites/software.rst
Mainly affects source code installations
> Update scheduler related notes; Environment performance tuning

- appendix/configure-env-vars.rst
- appendix/troubleshooting/index.rst
- install/elasticsearch.rst
- install/includes/manage-services.rst
- install/includes/nodejs/centos.rst
- install/includes/nodejs/debian.rst
- install/includes/nodejs/suse.rst
- install/includes/nodejs/ubuntu.rst
- install/package.rst
- install/source.rst
- install/source/include-environment.rst
- install/source/include-rvm-install-ruby.rst
- install/update.rst
- prerequisites/software.rst
This PR contains all upcoming changes for an easier merge upon release.
> Pre release 5 2

- admin/console.rst
- appendix/configure-env-vars.rst
Changelog:
* Add a warning block explaining `ZAMMAD_SAFE_MODE` environment variable with sample output.
> Fixes #290 - Add Zammad safe mode.

- appendix/configure-env-vars.rst
- install/includes/db-seed-base_url.rst
- install/source.rst
See commit https://github.com/zammad/zammad/commit/30ea2c309f2bbf89d38dbd54a5e88d110f4bca7b
> Add base URL tip in DB init section.

- install/package.rst
This should go straight to `main`, as it is already available.
> Added hint for Debian 12.

- api/role.rst
- index.rst
Porting from main to pre-release
> Fixes #223 - added roles endpoint

- install/docker-compose.rst
Follow-up for https://github.com/zammad/zammad-docker-compose/pull/366.
This should go to main, because it is already valid for the current stable.
> Document 'How to run rails/rake commands in containers'.

- README.md
Adjusted it to be conform with admin-/user-docs (but without the translation part)
> Maintenance: Redacting README.md

- install/includes/postgres-dependencies.rst
- install/includes/postgres-installation.rst
- install/package.rst
- prerequisites/software.rst
I hope I found all places where CentOS is mentioned / needs to be added.
> Maintenance: Add support for CentOS 9.

- prerequisites/software.rst
Put more visible than more configuration is required :-)
> Add an hint for proxy as more configuration is needed

- admin/console/other-useful-commands.rst
> Improved mail reprocessing docs.

- install/elasticsearch.rst
> Fix setting typo for elasticsearch password

- install/elasticsearch.rst
> Maintenance: Fix typo for elasticsearch password

- about/zammad.rst
- getting-started/configure-webserver.rst
- install/docker-compose.rst
- install/elasticsearch.rst
- install/includes/hosted-services.rst
- install/kubernetes.rst
- install/package.rst
- install/source.rst
- install/update.rst
- prerequisites/hardware.rst
- prerequisites/software.rst
> Fixes #582 - Added recommendation for hosted services

- admin/console.rst
- install/elasticsearch.rst
Reverts zammad/zammad-documentation#693
> Revert "Fixes #691 - Added command for adding specific ES index"
